services:
  teamj_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - teamj_db
    volumes:
      - './app:/app'
    entrypoint:
      - sh
      - '-c'
      - 'sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
  teamj_db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: teamj
      MYSQL_DATABASE: teamj_db
    ports:
      - '3306:3306'
    volumes:
      - './db_data:/var/lib/mysql'
