global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'fastapi-data' 
    static_configs: 
      - targets: ['teamj_backend:8000']
  - job_name: 'cAdvisor-data' 
    static_configs:  
      - targets: ['cadvisor:8080']